apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "physical-tracking-service.fullname" . }}-config
  labels:
    {{- include "physical-tracking-service.labels" . | nindent 4 }}
data:
  database.url: {{ .Values.config.database.url | quote }}
  database.username: {{ .Values.config.database.username | quote }}
  database.pool.size: {{ .Values.config.database.pool.size | quote }}
  database.pool.max-lifetime: {{ .Values.config.database.pool.maxLifetime | quote }}
  kafka.bootstrap-servers: {{ .Values.config.kafka.bootstrapServers | quote }}
  kafka.group-id: {{ .Values.config.kafka.groupId | quote }}
  rtls.enabled: {{ .Values.config.rtls.enabled | quote }}
  rtls.update-interval-ms: {{ .Values.config.rtls.updateIntervalMs | quote }}
